platform:
  - x86
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
install:
  - ps: Install-Product node 10 x86
  - npm install
build_script:
  - npm run dist
test: off
artifacts:
  - path: dist

